# Generated by Django 5.2.7 on 2025-10-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_borrowing_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
